name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest black codespell
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
    - run: black . --check || true
    - uses: codespell-project/actions-codespell@master
      with:
        skip: "*.json,*.png,*.gif,*.PNG,.git"
    - run: pip install -r requirements.txt || true
    - run: python -m pytest --auth=${{secrets.STARCLI_AUTH}}
